#!/bin/bash


# Unset any and all OS-set aliases for a predictable shell.
unalias -a


## General shell use ##

# Prettiness
alias ls='ls --group-directories-first --time-style=+"%Y-%m-%d_%H%M:%S" --color=auto'
alias df='df -h'
alias free='free -m'
alias grep='grep --color=tty'
alias fgrep='fgrep --color=tty'
alias egrep='egrep --color=tty'

# Safety
alias cp='cp -i' # Prompt before overwriting
alias mv='mv -i' # Ditto

# Shortcut for $EDITOR
alias emac="$EDITOR"

# Quickly retract Yakuake when it gets stuck (bug workaround)
alias a='qdbus org.kde.yakuake /yakuake/window org.kde.yakuake.toggleWindowState'


## Coding ##

# Git shortcuts
alias ga='git add'
alias gaa='git add -a'
alias gc='git commit'
alias gca='git commit -a'
alias gd='git diff'
alias gda='git diff -a'
alias gpom='git push origin master'
alias gs='git status'

# Format an entire Go project at once.
alias gofmtr="find . -type f | grep '\.go$' | xargs -r -n1 gofmt -w"

# Parallelize make with 6 cores.
alias make='make -j6'

# Ignore return values being _potentially_ masked. I'm that tired of
# that false positive.
alias shellcheck='shellcheck --exclude=SC2155'
