#!/bin/bash

# NOTE: This must be sourced (e.g., in your .bashrc) in order to work!

cdh() {
    if [ -z "$1" ]
    then
	. "$(cmpath cdh)"
    else
	# Find and source the actual command, passing the
	# argument to it.
	. "$(cmpath cdh)" "$1"
    fi
}
