#!/bin/bash

# Miscellaneous custom Bash stuff

# Set $LS_COLORS so ls is properly pretty.
eval "$(dircolors --bourne-shell)"

# Make sudo auto-complete with command and file names
complete -cf sudo

# Options that are apparently useful?
shopt -s cdspell
shopt -s checkwinsize
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s hostcomplete
shopt -s nocaseglob
