#!/bin/bash

# Miscellaneous custom Bash stuff

# Set $LS_COLORS so ls is properly pretty.
eval "$(dircolors --bourne-shell)"

# Completions
complete -cf sudo # Makes sudo auto-complete with command and file names
# Make cm* auto-complete with command names
complete -c cmcd
complete -c cmdir
complete -c cmedit
complete -c cmls
complete -c cmpath

# Options that are apparently useful?
shopt -s cdspell
shopt -s checkwinsize
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s hostcomplete
shopt -s nocaseglob
