#!/usr/bin/env bash
## shortcuts
# Convert certain scripts into functions for shell integration.

# Make functions that source given commands, enabling things like "cd"
# in the commands to have the desired effects in interactive shells.
local fn
for fn in cdh cdl cmcd mkcd pcd; do
    if [ "$DEBUG" = "true" ]; then
        echo "shortcut: $fn"
    fi
    # Example "cmd-foo" -> cmd-foo() { . "/path/to/cmd-foo" "$@"; }
    eval "$fn() { . \"$(cmpath "$fn")\" \"\$@\"; }"
done
