#!/bin/sh
# Git shortcuts
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gca='git commit --all'
alias gd='git diff'
alias gpom='git pull origin master && git push origin master'
alias gs='git status'
