#!/bin/sh
# Git shortcuts
alias ga='git add'
alias gaa='git add -a'
alias gc='git commit'
alias gca='git commit -a'
alias gd='git diff'
alias gda='git diff -a'
alias gpom='git pull origin master && git push origin master'
alias gs='git status'
