#!/bin/sh

## General aliases ##

# Shortcut for $EDITOR
alias emac="$EDITOR"

# Format an entire Go project at once.
alias gofmtr="find . -type f -name '*go' -print0 | xargs -0 -r -n1 gofmt -w"

# Parallelize make with 6 cores.
alias make='make -j6'
