#!/usr/bin/env bash
# Bash completion for bb2.py

_auto-lock() {
    local commands=(configure help install maybe-lock reinstall uninstall)
    COMPREPLY=($(compgen -W "${commands[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
}
complete -F _auto-lock auto-lock
