#!/usr/bin/env bash
# Bash completion for pm.sh

_pm() {
    ## Nope, not gonna use a much clunkier command that doesn't even
    ## handle mixed newline and space dilimitation when I know compgen
    ## is made for COMPREPLY.
    # shellcheck disable=SC2207
    COMPREPLY=($(compgen -W "$(pm list-commands)" -- "${COMP_WORDS[COMP_CWORD]}"))
}
complete -F _pm pm
