#!/usr/bin/env bash
# Make cm* and other commands auto-complete with command names
for __tmp_refola_scripts_completion_var in cmcd cmdir cmedit cmls cmpath cmss silent-fork; do
    complete -c "$__tmp_refola_scripts_completion_var"
done
unset __tmp_refola_scripts_completion_var

# mkcd's arg is close enough to what cd's completion suggests
complete -o nospace -F _cd mkcd
