#!/bin/bash
# Make cm* auto-complete with command names
complete -c cmcd
complete -c cmdir
complete -c cmedit
complete -c cmls
complete -c cmpath

# mkcd's arg is close enough to what cd's completion suggests
complete -o nospace -F _cd mkcd
